set(SRC_FILES
    App.cpp
    GameCore/GameManager.cpp
    GameCore/MainGame.cpp
    Character/BaseCharacter.cpp
    Character/HealthSystem.cpp
    Character/Enemy.cpp
    Character/PlayerDice.cpp
    Character/Dices/Warrior.cpp
    Character/Enemys/Frog.cpp
    EventSystem/BaseEventSystem.cpp
    Cards/CardSystem.cpp
    Cards/Card.cpp
    Cards/Variant/SwordCard.cpp
    Cards/Variant/BroadSwordCard.cpp
    Cards/Variant/SmallShieldCard.cpp
    Cards/RequireVariant/NoneRequire.cpp
    Cards/RequireVariant/ContainedDiceRequire.cpp
    Cards/RequireVariant/MaxRequire.cpp
    EventSystem/BattleSystem.cpp
    DiceUtils/Dice.cpp
    AI/EnemyAI.cpp
    AI/DumbAI.cpp
    Player/PlayerBattleInput.cpp
    UI/BattleUIManager.cpp
    UI/Utils/Slider.cpp
    UI/Utils/EffectBar.cpp
    UI/Utils/EffectIcon.cpp
    UI/CardsRenderer/CardRenderer.cpp
    UI/CardsRenderer/RequireSlotRenderer.cpp
)

set(INCLUDE_FILES
    App.hpp
    GameCore/GameManager.hpp
    GameCore/MainGame.hpp
    Character/BaseCharacter.hpp
    Character/HealthSystem.hpp
    Character/Enemy.hpp
    Character/PlayerDice.hpp
    Character/Dices/Warrior.hpp
    Character/Enemys/Frog.hpp
    EventSystem/BaseEventSystem.hpp
    EventSystem/BattleSystem.hpp
    EventSystem/EffectSystem.hpp
    Cards/CardSystem.hpp
    Cards/Card.hpp
    Cards/Variant/SwordCard.hpp
    Cards/Variant/BroadSwordCard.hpp
    Cards/Variant/SmallShieldCard.hpp
    Cards/RequireVariant/NoneRequire.hpp
    Cards/RequireVariant/ContainedDiceRequire.hpp
    Cards/RequireVariant/MaxRequire.hpp
    Cards/CardRequireSlot.hpp
    Cards/CardRegister.hpp
    Cards/CardFactory.hpp
    DiceUtils/Dice.hpp
    AI/DumbAI.hpp
    AI/EnemyAI.hpp
    Player/PlayerBattleInput.hpp
    UI/BattleUIManager.hpp
    ResourceConfig.hpp
    UI/Utils/Slider.hpp
    UI/Utils/EffectBar.hpp
    UI/Utils/EffectIcon.hpp
    UI/CardsRenderer/CardRenderer.hpp
    UI/CardsRenderer/RequireSlotRenderer.hpp
)

set(TEST_FILES
)
